version: 2
references:
  repo_restore_cache: &repo_restore_cache
    restore_cache:
      keys:
        - repo-{{ .Environment.CIRCLE_SHA1 }}
  repo_save_cache: &repo_save_cache
    save_cache:
      key: repo-{{ .Environment.CIRCLE_SHA1 }}-{{ epoch }}
      paths:
        - ~/gobrake
  unit: &unit
    run:
      name: Run unit tests
      command: go test

jobs:
  golangci_lint:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/gobrake
    steps:
      - checkout
      - <<: *repo_save_cache
      - run:
          name: Run GolangCI linting
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
            golangci-lint run
  "go1.11":
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/gobrake
    steps:
      - <<: *repo_restore_cache
      - <<: *unit
  "go1.12":
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/gobrake
    steps:
      - <<: *repo_restore_cache
      - <<: *unit
  "go1.13":
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/gobrake
    steps:
      - <<: *repo_restore_cache
      - <<: *unit
  "go1.14":
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/gobrake
    steps:
      - <<: *repo_restore_cache
      - <<: *unit

workflows:
  version: 2
  build:
    jobs:
      - golangci_lint
      - "go1.11":
          requires:
            - golangci_lint
      - "go1.12":
          requires:
            - golangci_lint
      - "go1.13":
          requires:
            - golangci_lint
      - "go1.14":
          requires:
            - golangci_lint
